# -*- coding: UTF-8 -*-
"""
  gfx.py
  Author : Jacek 'Szumak' Kotlarski --<szumak@virthost.pl>
  Created: 18.01.2024, 22:04:43
  
  Purpose: GFX storage class for tkinter
"""

from jsktoolbox.attribtool import ReadOnlyClass


class Pics(object, metaclass=ReadOnlyClass):
    """Pics - gfx 16x16."""

    CLIPBOARD_16: bytes = b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAdVBMVEUAAAD///8AAABZWVlQUFDa2tri4uKbm5u7u7vm5ub8/PxWVlbS0tLX19d9fX2jo6P09PTs7OwZGRmqqqpdXV0UFBQdHR0qKiqVlZVxcXFBQUFISEhoaGi5ubmDg4OwsLA8PDyMjIwkJCRjY2PHx8cODg4pKSmuzk7RAAAAAXRSTlMAQObYZgAAAAFiS0dEAIgFHUgAAAEbSURBVBgZARAB7/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASAiUAAAAAAAAAAAAAJSUAEhoAABcVABIlAAAAAAAlAAACAAAAAAIAACUAAAAAACUAAAAAAAAAAAAAJQAAAAAAJQAAAAAAAAAAAAAlAAAAAAAlAAAAAAAAABUAACUAAAAAACUAAAAAAAACAAAAAAAAAAAAJQAAAAAAAhcbGxsbGgAAAAAlAAAAAAAAIgAAAAAAAAAAACUAAAAAAAAAIAAAJQAAAAAAJQAAAAAAAAAAAAAlAAAAAAAlAAAAAAAAAAAAACUAAAAAACUAAAAAAAAAAAAAJQAAAAAAAAICAgICAgICAgIAAAAAAAAAAAAAAAAAAAAAAAAAANWABOLo6Qk0AAAAAElFTkSuQmCC"
    PERMIT_16: bytes = b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAdVBMVEUAAAD///8AAACtra309PT7+/vb29vQ0NCLi4swMDB0dHR9fX0+Pj719fXn5+fv7+/q6uplZWW6urrZ2dmysrLHx8deXl5NTU2FhYWTk5O4uLgWFhampqZDQ0MREREpKSlra2sfHx9TU1PLy8udnZ03NzdQUFAmXm3/AAAAAXRSTlMAQObYZgAAAAFiS0dEAIgFHUgAAAEbSURBVBgZARAB7/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXFxcXFxcXFxcXFxcXFwAAABYAAAAAAAAAAAAAAAAWAAAAFgACAgICAgICAgICDBYAAAAWAAAAAAAAAAAAAAAAFgAAABYAGxsbGxsbGxsbGwAWAAAAFgACAgICAgICAgICABYAAAAWAAAAAAAAAAAAAAAAFgAAABYAIh4mAAAhISEhHwAWAAAAFgAJAh0AAAAAAAAAABYAAAAWAB0lFgAAAgICAgIAFgAAABYAAAAAAAAAAAAAAAAWAAAAFxcXFxcXFxcXFxcXFxcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAK6ZBxKi3ePNAAAAAElFTkSuQmCC"


# #[EOF]#######################################################################
